version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: btc-account-owner
      POSTGRES_PASSWORD: sTr_oNgPwD!!1

  # this second PostgresSQL is used when running test
  postgres-db-test:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: btc-account
      POSTGRES_USER: btc-account-owner
      POSTGRES_PASSWORD: sTr_oNgPwD!!1

# See dockerhub for different versions of kafka and zookeeper
# https://hub.docker.com/r/wurstmeister/kafka/
# https://hub.docker.com/r/wurstmeister/zookeeper/
  zookeeper:
    image: zookeeper:3.6.2
    ports:
      - "2181:2181"

